Rate limiter and cache middleware
getAlby/lndhub.go pull request #131
Opened 2022-03-10 22:52 UTC by skosito

2022-03-10 22:53 UTC, skosito commented on main.go
> +	return middleware.RateLimiter(middleware.NewRateLimiterMemoryStoreWithConfig(config))
if i just pass rate.Every(10 * time.Second) that is same as 0.1 and it is treated as 0
only way to do this it seems is to set rate to 0.1, and burst to 1, and it is acting as 1 every 10 seconds

tested it using postman with /create endpoint

2022-03-10 22:54 UTC, skosito commented on main.go
> +	e.GET("/", homeController.Home, createCacheClient().Middleware())
tested by checking that only first time home endpoint is hit and then it is cached, please check parameters, i took default

2022-03-10 22:55 UTC, skosito commented on main.go
> +	secured := e.Group("", tokens.Middleware(c.JWTSecret), middleware.RateLimiter(middleware.NewRateLimiterMemoryStore(1)))
just put one each second for all secured, it can easily be changed with your suggestion

2022-03-10 22:56 UTC, skosito commented on go.sum
>  github.com/BurntSushi/xgb v0.0.0-20160522181843-27f122750802/go.mod h1:IVnqGOEym/WlBOVXweHU+Q+/VP0lqqI8lqeDx9IjBqo=
after running go mod tidy these indirect dependencies were added

2022-03-10 22:58 UTC, skosito commented on main.go
>  	e.POST("/auth", controllers.NewAuthController(svc).Auth)
something for auth? maybe doesn't make sense

2022-03-14 09:28 UTC, kiwiidb requested changes
Great work, I would just change a couple of things:

- Make the timoutSeconds configurable for rate limits, both the strict limit and the less strict limit. The caching is fine as it is, these params don't need to be in the config.
- Put the `/keysend` endpoint also on the strict rate limit.
- Put the `/getinfo` endpoint under the caching middleware.
- Make the default timeout for the less-strict rate limit more relaxed: 10 requests / second should be fine for calls that don't hit the Lightning node.

2022-03-15 11:42 UTC, skosito commented
> * 
> * Put the

@kiwiidb thanks for review, fixed the comments, please check again

2022-03-16 07:38 UTC, kiwiidb approved these changes

2022-03-16 07:38 UTC, merged